$script:HealthStatus = @{
    0 = 'Unspecified'
    1 = 'Healthy'
    2 = 'Error'
    3 = 'Warning'
    4 = 'N/A'
    5 = 'Retrying'
    6 = 'Blocker'
}

$script:SeverityOrder = @(6, 2, 3, 5, 0, 4)

$script:SeverityColor = @{
    6 = 'Red'
    2 = 'Red'
    3 = 'Yellow'
    5 = 'Cyan'
    0 = 'Gray'
    4 = 'DarkGray'
}

$script:AssetMonitorType = @{
    1  = 'Not Monitored'
    2  = 'Segment Server'
    4  = 'Unsupported OS'
    5  = 'Unmonitorable'
    6  = 'Unmonitorable'
    7  = 'Cloud Connector'
    8  = 'Not Monitored (Ansible Unreachable)'
    9  = 'Not Monitored (Cloud Connector Uninstalled)'
    10 = 'Not Monitored (Cloud Connector Required)'
    12 = 'Inactive Entity'
    13 = 'Stalked Externally'
    14 = 'Lightweight Agent'
}

$script:IssueCodeNames = @{
    0    = 'Unspecified'
    1    = 'Access Denied'
    2    = 'WMI Corrupted'
    3    = 'URL Filtering Issue'
    4    = 'Out of Disk Space'
    5    = 'Setup Script Failed'
    6    = 'Slow MFA'
    7    = 'Driver Not Loaded'
    8    = 'Service Not Running'
    9    = 'Agent Not Responding'
    10   = 'Policy Not Applied'
    11   = 'Certificate Error'
    12   = 'Network Unreachable'
    13   = 'Authentication Failure'
    14   = 'Firewall Rule Conflict'
    15   = 'GPO Conflict'
    16   = 'DNS Resolution Failed'
    17   = 'Clock Skew'
    18   = 'Insufficient Permissions'
    19   = 'Incompatible OS'
    20   = 'High CPU Usage'
    21   = 'High Memory Usage'
    22   = 'License Limit Reached'
    23   = 'Agent Update Required'
    24   = 'Connectivity Issue'
    25   = 'Configuration Error'
    26   = 'Hardware Incompatibility'
    27   = 'Kernel Module Error'
    28   = 'Audit Log Failure'
    29   = 'Identity Provider Error'
    30   = 'MFA Provider Unavailable'
    31   = 'Certificate Expired'
    32   = 'Token Validation Failed'
    33   = 'LDAP Connection Failed'
    34   = 'Database Error'
    36   = 'Unknown Agent Error'
    1000 = 'Internal Error'
    1001 = 'Transient Error'
    1002 = 'Unsupported Platform'
}
